meta_product_name: "Seer"
meta_title: "Seer - Discover your destiny!"
meta_description: "Looking for love? Seeking a new job? Just bought a new house? Seer is here to help guide you through your various paths in life by providing some divine inspiration!"
meta_image: "logo.png" # should exist in `app/assets/images/`
twitter_account: "@seer_twitter_account"   # required for Twitter Cards
